# Generated by Django 3.0.9 on 2020-08-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titleratings', '0003_auto_20200803_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='UserRating',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
