# Generated by Django 3.0.9 on 2020-08-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titleratings', '0005_auto_20200803_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
