# Generated by Django 3.0.9 on 2020-08-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titleratings', '0007_auto_20200806_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='description',
            field=models.TextField(default=True),
        ),
    ]
