# Generated by Django 3.0.9 on 2020-08-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titleratings', '0008_ratings_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
