# Generated by Django 3.0.9 on 2020-08-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titleratings', '0009_auto_20200807_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
