# Generated by Django 3.0.9 on 2020-08-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titleratings', '0011_auto_20200813_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
