# Generated by Django 3.0.9 on 2020-08-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titleratings', '0014_auto_20200813_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
