# Generated by Django 3.0.9 on 2020-08-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titleratings', '0015_auto_20200813_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='description',
            field=models.CharField(blank=True, default=True, max_length=1000, null=True),
        ),
    ]
