# Generated by Django 3.0.9 on 2020-08-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titleratings', '0016_auto_20200813_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='photo',
            field=models.ImageField(blank=True, default=True, null=True, upload_to='images/'),
        ),
    ]
