# Generated by Django 3.0.9 on 2020-08-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titleratings', '0018_auto_20200813_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='photo',
            field=models.ImageField(default='pending.jpg', upload_to='images/'),
        ),
    ]
