# Generated by Django 3.0.9 on 2020-09-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titleratings', '0019_auto_20200813_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameofYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
