# Generated by Django 3.0.9 on 2020-09-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titleratings', '0020_gameofyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameofyear',
            name='photo',
            field=models.ImageField(default='pending.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='gameofyear',
            name='year',
            field=models.IntegerField(default=20, max_length=100),
            preserve_default=False,
        ),
    ]
