# Generated by Django 3.0.9 on 2020-09-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titleratings', '0021_auto_20200903_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameofyear',
            name='publisher',
            field=models.CharField(default=22, max_length=100),
            preserve_default=False,
        ),
    ]
