# Generated by Django 3.0.9 on 2020-09-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Titleratings', '0023_auto_20200909_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='details',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
