# Generated by Django 3.0.9 on 2020-11-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingGames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('platform', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='/staticfiles/images/pending.jpg', upload_to='images/')),
                ('release_date', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
    ]
